#ifndef _ITF_PRECOMPILED_ONLINETRACKINGADAPTER_WIN32_H_
#define _ITF_PRECOMPILED_ONLINETRACKINGADAPTER_WIN32_H_
#include "core/enginecommon.h"
#include "core/memory/memory.h"

#endif //_ITF_PRECOMPILED_ONLINETRACKINGADAPTER_WIN32_H_