/*
* This code is generated by np-universal-data-system-codegen.exe. 
* 
* It is available to edit this file but may cause malfunctions. 
*/
#ifndef _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_
#define _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_

#include <np.h>

#ifdef __cplusplus
extern "C" {
#endif /* ifdef __cplusplus */

/*****************/
/* _UnlockTrophy */
/*****************/

int sceNpUniversalDataSystemCodegenPost_UnlockTrophy(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id
    );

/*************************/
/* _UpdateTrophyProgress */
/*************************/

int sceNpUniversalDataSystemCodegenPost_UpdateTrophyProgress(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id,
    int32_t _trophy_progress
    );

/*****************/
/* activityStart */
/*****************/

int sceNpUniversalDataSystemCodegenPostactivityStart(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

/***************/
/* activityEnd */
/***************/

int sceNpUniversalDataSystemCodegenPostactivityEnd(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

/******************/
/* activityResume */
/******************/

int sceNpUniversalDataSystemCodegenPostactivityResume(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

/*********************/
/* activityTerminate */
/*********************/

int sceNpUniversalDataSystemCodegenPostactivityTerminate(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle
    );

#ifdef __cplusplus
}
#endif /* ifdef __cplusplus */

#endif /* _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_ */
