/*
* This code is generated by np-universal-data-system-codegen.exe. 
* 
* It is available to edit this file but may cause malfunctions. 
*/
#include "np_universal_data_system_codegen.h"
/*****************/
/* _UnlockTrophy */
/*****************/

int sceNpUniversalDataSystemCodegenPost_UnlockTrophy(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("_UnlockTrophy", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetInt32(_prop, "_trophy_id", _trophy_id);
    if(_ret < 0) {
        goto _error;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

/*************************/
/* _UpdateTrophyProgress */
/*************************/

int sceNpUniversalDataSystemCodegenPost_UpdateTrophyProgress(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id,
    int32_t _trophy_progress
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("_UpdateTrophyProgress", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetInt32(_prop, "_trophy_id", _trophy_id);
    if(_ret < 0) {
        goto _error;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetInt32(_prop, "_trophy_progress", _trophy_progress);
    if(_ret < 0) {
        goto _error;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

/*****************/
/* activityStart */
/*****************/

int sceNpUniversalDataSystemCodegenPostactivityStart(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("activityStart", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetString(_prop, "activityId", activityId);
    if(_ret < 0) {
        goto _error;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

/***************/
/* activityEnd */
/***************/

int sceNpUniversalDataSystemCodegenPostactivityEnd(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("activityEnd", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetString(_prop, "activityId", activityId);
    if(_ret < 0) {
        goto _error;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

/******************/
/* activityResume */
/******************/

int sceNpUniversalDataSystemCodegenPostactivityResume(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("activityResume", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }
    _ret = sceNpUniversalDataSystemEventPropertyObjectSetString(_prop, "activityId", activityId);
    if(_ret < 0) {
        goto _error;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

/*********************/
/* activityTerminate */
/*********************/

int sceNpUniversalDataSystemCodegenPostactivityTerminate(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle
    )
{
    int _ret = 0;
    SceNpUniversalDataSystemEvent *_event = NULL;
    SceNpUniversalDataSystemEventPropertyObject *_prop = NULL;
    uint64_t _options_post_event = 0x0;
    _options_post_event |= SCE_NP_UNIVERSAL_DATA_SYSTEM_POST_EVENT_OPTION_GENERATED_BY_CODEGEN; /* DO NOT modify. This is for internal use. */
    _ret = sceNpUniversalDataSystemCreateEvent("activityTerminate", NULL, &_event, &_prop);
    if(_ret < 0) {
        return _ret;
    }

    _ret = sceNpUniversalDataSystemPostEvent(_context, _handle, _event, _options_post_event);
    if (_ret < 0) {
        goto _error;
    }
    sceNpUniversalDataSystemDestroyEvent(_event);
    return SCE_OK;

_error:
    if (_event) {
        sceNpUniversalDataSystemDestroyEvent(_event);
    }
    return _ret;
}

