/*
* This code is generated by np-universal-data-system-codegen.exe. 
* 
* It is available to edit this file but may cause malfunctions. 
*/
#ifndef _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_
#define _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_

#include <np.h>

#ifdef __cplusplus
extern "C" {
#endif /* ifdef __cplusplus */

/*****************/
/* _UnlockTrophy */
/*****************/

int sceNpUniversalDataSystemCodegenPost_UnlockTrophy(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id
    );

/*************************/
/* _UpdateTrophyProgress */
/*************************/

int sceNpUniversalDataSystemCodegenPost_UpdateTrophyProgress(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    int32_t _trophy_id,
    int32_t _trophy_progress
    );

/*****************/
/* activityStart */
/*****************/

int sceNpUniversalDataSystemCodegenPostactivityStart(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

/***************/
/* activityEnd */
/***************/

typedef struct SceNpUniversalDataSystemCodegenactivityEndOption SceNpUniversalDataSystemCodegenactivityEndOption;
void sceNpUniversalDataSystemCodegenactivityEndOptionInit(
    SceNpUniversalDataSystemCodegenactivityEndOption *_option
    );
void sceNpUniversalDataSystemCodegenactivityEndOptionSetoutcome(
    SceNpUniversalDataSystemCodegenactivityEndOption *_option,
    const char *outcome
    );
struct SceNpUniversalDataSystemCodegenactivityEndOption {
    const char *outcome;
    bool _useoutcome;
};
int sceNpUniversalDataSystemCodegenPostactivityEnd(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

int sceNpUniversalDataSystemCodegenPostactivityEndWithOption(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId,
    const SceNpUniversalDataSystemCodegenactivityEndOption *_option
    );

/******************/
/* activityResume */
/******************/

typedef struct SceNpUniversalDataSystemCodegenactivityResumeOption SceNpUniversalDataSystemCodegenactivityResumeOption;
void sceNpUniversalDataSystemCodegenactivityResumeOptionInit(
    SceNpUniversalDataSystemCodegenactivityResumeOption *_option
    );
void sceNpUniversalDataSystemCodegenactivityResumeOptionSetcompletedActivities(
    SceNpUniversalDataSystemCodegenactivityResumeOption *_option,
    const char **completedActivities,
    size_t _sizecompletedActivities
    );
void sceNpUniversalDataSystemCodegenactivityResumeOptionSetinProgressActivities(
    SceNpUniversalDataSystemCodegenactivityResumeOption *_option,
    const char **inProgressActivities,
    size_t _sizeinProgressActivities
    );
struct SceNpUniversalDataSystemCodegenactivityResumeOption {
    const char **completedActivities;
    size_t _sizecompletedActivities;
    bool _usecompletedActivities;
    const char **inProgressActivities;
    size_t _sizeinProgressActivities;
    bool _useinProgressActivities;
};
int sceNpUniversalDataSystemCodegenPostactivityResume(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId
    );

int sceNpUniversalDataSystemCodegenPostactivityResumeWithOption(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle,
    const char *activityId,
    const SceNpUniversalDataSystemCodegenactivityResumeOption *_option
    );

/*********************/
/* activityTerminate */
/*********************/

int sceNpUniversalDataSystemCodegenPostactivityTerminate(
    SceNpUniversalDataSystemContext _context,
    SceNpUniversalDataSystemHandle _handle
    );

#ifdef __cplusplus
}
#endif /* ifdef __cplusplus */

#endif /* _SCE_NP_UNIVERSAL_DATA_SYSTEM_CODEGEN_H_ */
