#ifndef __AUDIOMIDDLEWAREADAPTER_ENUMS_H__
#define __AUDIOMIDDLEWAREADAPTER_ENUMS_H__


#ifndef ITF_NAMESPACE_BEGIN
    #define ITF_NAMESPACE_BEGIN()                           namespace ITF {
    #define ITF_NAMESPACE_END()                             }

    #define DECLARE_ENUM_BEGIN(__enumName)                  enum __enumName {
    #define ENUM_ITEM_AND_VALUE(__itemName, __itemValue)    __itemName= __itemValue,
    #define ENUM_ITEM(__itemName)                           __itemName,
    #define DECLARE_ENUM_END()                              };
#endif


ITF_NAMESPACE_BEGIN()

	DECLARE_ENUM_BEGIN(AudioSyncPlayAt)
	    ENUM_ITEM_AND_VALUE(AUDIO_SYNC_PLAY_IMMEDIATE, 0)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_NEXT_GRID)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_NEXT_BAR)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_NEXT_BEAT)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_NEXT_CUE)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_NEXT_CUSTOM_CUE)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_ENTRY_CUE)
		ENUM_ITEM(AUDIO_SYNC_PLAY_AT_EXIT_CUE)
		ENUM_ITEM(AUDIO_SYNC_PLAY_COUNT)
	DECLARE_ENUM_END()


#define SERIALIZE_SYNCPLAY_TYPE(__name, __val) \
		SERIALIZE_ENUM_BEGIN(__name, __val); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_IMMEDIATE); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_NEXT_GRID); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_NEXT_BAR); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_NEXT_BEAT); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_NEXT_CUE); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_NEXT_CUSTOM_CUE); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_ENTRY_CUE); \
		SERIALIZE_ENUM_VAR(AUDIO_SYNC_PLAY_AT_EXIT_CUE); \
		SERIALIZE_ENUM_END();


	DECLARE_ENUM_BEGIN(MetronomeType)
	    ENUM_ITEM_AND_VALUE(METRONOME_TYPE_DEFAULT,0)
		ENUM_ITEM(METRONOME_TYPE_MENU)
		ENUM_ITEM(METRONOME_TYPE_GAMEPLAY)
        ENUM_ITEM(METRONOME_TYPE_LUMKING)
		ENUM_ITEM(METRONOME_TYPE_COUNT)
		ENUM_ITEM(METRONOME_TYPE_INVALID)
    DECLARE_ENUM_END()


        
#define SERIALIZE_METRONOMETYPE(__name, __val) \
		SERIALIZE_ENUM_BEGIN(__name, __val); \
		SERIALIZE_ENUM_VAR(METRONOME_TYPE_DEFAULT); \
		SERIALIZE_ENUM_VAR(METRONOME_TYPE_MENU); \
        SERIALIZE_ENUM_VAR(METRONOME_TYPE_GAMEPLAY); \
        SERIALIZE_ENUM_VAR(METRONOME_TYPE_LUMKING); \
		SERIALIZE_ENUM_VAR(METRONOME_TYPE_INVALID); \
		SERIALIZE_ENUM_END();


	DECLARE_ENUM_BEGIN(AudioPauseID)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_NONE			    , 0x00000000)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_GAMEPLAY		    , 0x00000001)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_CUTSCENE		    , 0x00000002)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_MENU			    , 0x00000004)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_TRC				, 0x00000008)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_VIDEO			, 0x00000010)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_DEBUG			, 0x00000020)
		ENUM_ITEM_AND_VALUE(AUDIOPAUSE_WIIU_BACKGROUND  , 0x00000040)
    DECLARE_ENUM_END()


	DECLARE_ENUM_BEGIN(AudioDeviceID)
		ENUM_ITEM_AND_VALUE(AUDIODEVICE_TV, 0)
		ENUM_ITEM(AUDIODEVICE_DRC_0)
		ENUM_ITEM(AUDIODEVICE_DRC_1)
		ENUM_ITEM(AUDIODEVICE_HEADPHONE)
    DECLARE_ENUM_END()


	DECLARE_ENUM_BEGIN(AudioItemType)
		ENUM_ITEM_AND_VALUE(AUDIO_ITEM_WWISE_EVENT, 0)
		ENUM_ITEM(AUDIO_ITEM_WWISE_GAME_PARAMETER)
		ENUM_ITEM(AUDIO_ITEM_WWISE_STATE_GROUP)
		ENUM_ITEM(AUDIO_ITEM_WWISE_STATE)
		ENUM_ITEM(AUDIO_ITEM_WWISE_SWITCH_GROUP)
		ENUM_ITEM(AUDIO_ITEM_WWISE_SWITCH)
		ENUM_ITEM(AUDIO_ITEM_WWISE_TRIGGER)
		ENUM_ITEM(AUDIO_ITEM_WWISE_DIALOGUE_EVENT)
		ENUM_ITEM(AUDIO_ITEM_WWISE_AUXBUS)
		ENUM_ITEM(AUDIO_ITEM_WWISE_BUS)
		ENUM_ITEM(AUDIO_ITEM_WWISE_EFFECT)
		ENUM_ITEM(AUDIO_ITEM_TYPE_COUNT)
		ENUM_ITEM(AUDIO_ITEM_TYPE_INVALID)
    DECLARE_ENUM_END()


	DECLARE_ENUM_BEGIN(AudioEngineEvent)
		ENUM_ITEM_AND_VALUE(AUDIO_ENGEVT_WWISE_PAUSE_GAMEPLAY, 0)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_CUTSCENE)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_MENU)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_TRC)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_VIDEO)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_DEBUG)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_PAUSE_WIIU)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_GAMEPLAY)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_CUTSCENE)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_MENU)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_TRC)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_VIDEO)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_DEBUG)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_RESUME_WIIU)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_STOP_ALL)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_START_MAP)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_MUTE_ALL)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_UNMUTE_ALL)
        ENUM_ITEM(AUDIO_ENGEVT_WWISE_CHECK_POINT_LOAD)
        ENUM_ITEM(AUDIO_ENGEVT_WWISE_RELOAD_MAP)
        ENUM_ITEM(AUDIO_ENGEVT_WWISE_HOT_RELOAD_MAP)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_SKIP_CINE)
		ENUM_ITEM(AUDIO_ENGEVT_WWISE_QUITFROMGAME)
        ENUM_ITEM(AUDIO_ENGEVT_COUNT)
		ENUM_ITEM(AUDIO_ENGEVT_INVALID)
    DECLARE_ENUM_END()


	DECLARE_ENUM_BEGIN(AudioSignal)
		ENUM_ITEM_AND_VALUE(AUDIO_SIG_START_MAP,  0)
		ENUM_ITEM(AUDIO_SIG_RELOAD_MAP)
		ENUM_ITEM(AUDIO_SIG_HOT_RELOAD_MAP)
		ENUM_ITEM(AUDIO_SIG_BEGIN_GENERATE_BANK)
		ENUM_ITEM(AUDIO_SIG_END_GENERATE_BANK)
		ENUM_ITEM(AUDIO_SIG_CONFIG_HAS_CHANGED)
        ENUM_ITEM(AUDIO_SIG_CHECK_POINT_LOAD)
		ENUM_ITEM(AUDIO_SIG_SKIP_CINE)
        ENUM_ITEM(AUDIO_SIG_STOP_ALL)
		ENUM_ITEM(AUDIO_SIG_STOP_ALL_QUITFROMGAME)
		ENUM_ITEM(AUDIO_SIG_COUNT)
    DECLARE_ENUM_END()


	DECLARE_ENUM_BEGIN(AudioBusSlotID)
		ENUM_ITEM_AND_VALUE(AUDIO_BUS_SLOT_0, 0)
		ENUM_ITEM(AUDIO_BUS_SLOT_1)
		ENUM_ITEM(AUDIO_BUS_SLOT_2)
		ENUM_ITEM(AUDIO_BUS_SLOT_3)
		ENUM_ITEM(AUDIO_BUS_SLOT_COUNT)
    DECLARE_ENUM_END()


    DECLARE_ENUM_BEGIN(AudioRtpcType)
        ENUM_ITEM_AND_VALUE(AUDIO_RTPC_GLOBAL, 0)
        ENUM_ITEM(AUDIO_RTPC_LOCAL)
        ENUM_ITEM(AUDIO_RTPC_SWITCH)
        ENUM_ITEM(AUDIO_RTPC_STATE)
        ENUM_ITEM(AUDIO_RTPC_DISTANCE_EMITER_LISTENER)
        ENUM_ITEM_AND_VALUE(AUDIO_RTPC_INVALID, 0x0FFFFFFF)
    DECLARE_ENUM_END()

#define SERIALIZE_AUDIO_RTPC_TYPE(__member_name, __member) \
        SERIALIZE_ENUM_BEGIN(__member_name, __member); \
        SERIALIZE_ENUM_VAR(AUDIO_RTPC_LOCAL); \
        SERIALIZE_ENUM_VAR(AUDIO_RTPC_GLOBAL); \
        SERIALIZE_ENUM_VAR(AUDIO_RTPC_SWITCH); \
        SERIALIZE_ENUM_VAR(AUDIO_RTPC_STATE); \
        SERIALIZE_ENUM_VAR(AUDIO_RTPC_DISTANCE_EMITER_LISTENER); \
        SERIALIZE_ENUM_END();


    DECLARE_ENUM_BEGIN(AudioMultiPositionMode)
        ENUM_ITEM_AND_VALUE(AUDIO_MULTIPOSITION_MODE_SINGLE_SOURCE,0)
        ENUM_ITEM(AUDIO_MULTIPOSITION_MODE_MULTI_SOURCES)
        ENUM_ITEM(AUDIO_MULTIPOSITION_MODE_MULTI_DIRECTIONS)
    DECLARE_ENUM_END()

#define SERIALIZE_AUDIOMULTIPOSITIONMODE(__name, __val) \
    SERIALIZE_ENUM_BEGIN(__name, __val); \
        SERIALIZE_ENUM_VAR(AUDIO_MULTIPOSITION_MODE_SINGLE_SOURCE); \
        SERIALIZE_ENUM_VAR(AUDIO_MULTIPOSITION_MODE_MULTI_SOURCES); \
        SERIALIZE_ENUM_VAR(AUDIO_MULTIPOSITION_MODE_MULTI_DIRECTIONS); \
    SERIALIZE_ENUM_END();


ITF_NAMESPACE_END()


#undef ITF_NAMESPACE_BEGIN
#undef ITF_NAMESPACE_END
#undef DECLARE_ENUM_BEGIN
#undef ENUM_ITEM_AND_VALUE
#undef ENUM_ITEM
#undef DECLARE_ENUM_END


#endif // __AUDIOMIDDLEWAREADAPTER_ENUMS_H__
