#ifndef _ITF_RAY_GAMEPLAYTYPES_H_
#define _ITF_RAY_GAMEPLAYTYPES_H_

namespace ITF
{

static const u32 s_maxPlayers = 4;


enum EReceivedHitType
{
    RECEIVEDHITTYPE_UNKNOWN         = -1,
    RECEIVEDHITTYPE_FRONTPUNCH      = 0,
    RECEIVEDHITTYPE_UPPUNCH         = 1,
    RECEIVEDHITTYPE_EJECTY          = 2,
    RECEIVEDHITTYPE_EJECTXY         = 3,
    RECEIVEDHITTYPE_HURTBOUNCE      = 4,
    RECEIVEDHITTYPE_DARKTOONIFY     = 5,
    RECEIVEDHITTYPE_EARTHQUAKE      = 6,
    RECEIVEDHITTYPE_SHOOTER         = 7,
    RECEIVEDHITTYPE_CRUSH           = 8,
    RECEIVEDHITTYPE_CHARGE_PUNCH    = 9,
    ENUM_FORCE_SIZE_32(EReceivedHitType)
};

#define SERIALIZE_RECEIVEDHITTYPE(name,val) \
SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_UNKNOWN); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_FRONTPUNCH); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_UPPUNCH); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_EJECTXY); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_HURTBOUNCE); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_DARKTOONIFY); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_EARTHQUAKE); \
    SERIALIZE_ENUM_VAR(RECEIVEDHITTYPE_SHOOTER); \
SERIALIZE_ENUM_END();


enum EHitSide
{
    HITSIDE_ABOVE,
    HITSIDE_FRONT,
    HITSIDE_BELOW,
    HITSIDE_BACK,
    ENUM_FORCE_SIZE_32(EHitSide)
};

enum EPunchType
{
    PUNCHTYPE_CHARGE                = 0,
    PUNCHTYPE_CRUSH                 = 1,
    PUNCHTYPE_CROUCHKICK            = 2,
    PUNCHTYPE_TORNADO               = 3,
    PUNCHTYPE_REPEATING             = 4,
    PUNCHTYPE_SPIN                  = 5,
    PUNCHTYPE_UTURNKICK             = 7,
    PUNCHTYPE_UPPERKICK             = 9,
    PUNCHTYPE_REDUCEDSIZE           = 11,
	PUNCHTYPE_U32_INVALID           = -1,
    ENUM_FORCE_SIZE_32(EPunchType)
};

#define SERIALIZE_PUNCHTYPE(name,val) \
SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_CHARGE); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_CRUSH); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_CROUCHKICK); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_TORNADO); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_REPEATING); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_SPIN); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_UTURNKICK); \
    SERIALIZE_ENUM_VAR(PUNCHTYPE_UPPERKICK); \
SERIALIZE_ENUM_END();

enum EActionCoopMode
{
    ACTIONCOOPMODE_NONE             = 0,
    ACTIONCOOPMODE_MAIN             = 1,
    ACTIONCOOPMODE_VICTIM           = 2,
    ACTIONCOOPMODE_MAIN_VICTIM      = 3,
    ENUM_FORCE_SIZE_32(EActionCoopMode)
};

enum EStance
{
    STANCE_STAND,
    STANCE_HANG,
    STANCE_CLIMB,
    STANCE_HELICO,
    STANCE_WALLSLIDE,
    STANCE_SUPPORT,
    STANCE_SWIM,
    STANCE_SWING,
    ENUM_FORCE_SIZE_32(EStance)
};

enum EOrientationPose
{
    ORIENTATION_VERTICAL,
    ORIENTATION_HORIZONTAL,
    ENUM_FORCE_SIZE_32(EOrientationPose)
};

enum EActionPose
{
    ACTIONPOSE_STAND,
    ACTIONPOSE_FIGHT,
    ACTIONPOSE_AFRAID,
    ENUM_FORCE_SIZE_32(EActionPose)
};

enum EMoodZone
{
    MOODZONE_NONE,
    MOODZONE_AFRAID,
    ENUM_FORCE_SIZE_32(EMoodZone)
};

enum EUturnType
{
    UTURNTYPE_NONE = 0,
    UTURNTYPE_GROUND = 1,
    UTURNTYPE_AIR = 2,
    UTURNTYPE_SWIM = 3,
    UTURNTYPE_CLIMB = 5,
    ENUM_FORCE_SIZE_32(EUturnType)
};

enum EPunchReleaseResult
{
    PUNCHRELEASERESULT_NOIMPACT,
    PUNCHRELEASERESULT_IMPACT,
    PUNCHRELEASERESULT_FAIL,
    ENUM_FORCE_SIZE_32(EPunchReleaseResult)
};

enum EDeathType
{
    DEATHTYPE_NONE,
    DEATHTYPE_INFINITEFALL,
    DEATHTYPE_REGULARDEATH,
    ENUM_FORCE_SIZE_32(EDeathType)
};

enum EHitNature
{
    HITNATURE_ENEMY,
    HITNATURE_ENVIRONMENTCRUSH,
    HITNATURE_ENVIRONMENTDAMAGE,
    HITNATURE_UNKNOWN,
};

enum BounceType
{
    BOUNCETYPE_NONE = 0,
    BOUNCETYPE_ENEMY = 1,
    BOUNCETYPE_BUMPER = 2,
    BOUNCETYPE_POLYLINE = 3,
    BOUNCETYPE_WAVE = 4,
    BOUNCETYPE_WINDTUNEL = 5,
    BOUNCETYPE_TALKINGHAT = 6,
    ENUM_FORCE_SIZE_32(BounceType)
};

#define SERIALIZE_BOUNCETYPE(name,val) \
    SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_NONE); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_ENEMY); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_BUMPER); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_POLYLINE); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_WAVE); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_WINDTUNEL); \
    SERIALIZE_ENUM_VAR(BOUNCETYPE_TALKINGHAT); \
    SERIALIZE_ENUM_END();

enum AirPose
{
    AIRPOSE_UP,
    AIRPOSE_MIDDLE,
    AIRPOSE_DOWN,
    AIRPOSE_SURFING,
    AIRPOSE_HOVER,
    ENUM_FORCE_SIZE_32(AirPose)
};

enum BounceReactType
{
    BOUNCEREACTTYPE_NONE,
    BOUNCEREACTTYPE_AUTO,
    BOUNCEREACTTYPE_SYNCHRO,
    BOUNCEREACTTYPE_CRUSH,
    ENUM_FORCE_SIZE_32(BounceReactType)
};

enum BTAIOrderType
{
    BTAIORDER_UNKNOWN = 0,
    BTAIORDER_WAITFORPLAYER,
    BTAIORDER_WAITFORLAST,
    BTAIORDER_WAITWHILEACTORSALIVE,
    BTAIORDER_SETTARGETWAYPOINT,
    BTAIORDER_PEDESTAL,
    BTAIORDER_SETRESPAWNPOINT,
    BTAIORDER_DETECTIONAREA,
    BTAIORDER_REMOVECURRENTORDER,
    ENUM_FORCE_SIZE_32(BTAIOrderType)
};

#define SERIALIZE_RAY_BTAIORDERTYPE(name,val) \
    SERIALIZE_ENUM_BEGIN(name,val); \
        SERIALIZE_ENUM_VAR(BTAIORDER_WAITFORPLAYER); \
        SERIALIZE_ENUM_VAR(BTAIORDER_WAITFORLAST); \
        SERIALIZE_ENUM_VAR(BTAIORDER_WAITWHILEACTORSALIVE); \
        SERIALIZE_ENUM_VAR(BTAIORDER_SETTARGETWAYPOINT); \
        SERIALIZE_ENUM_VAR(BTAIORDER_PEDESTAL); \
        SERIALIZE_ENUM_VAR(BTAIORDER_SETRESPAWNPOINT); \
        SERIALIZE_ENUM_VAR(BTAIORDER_DETECTIONAREA); \
        SERIALIZE_ENUM_VAR(BTAIORDER_REMOVECURRENTORDER); \
    SERIALIZE_ENUM_END();


#define SERIALIZE_RAY_BOUNCETYPE(name,val) \
    SERIALIZE_ENUM_BEGIN(name,val); \
        SERIALIZE_ENUM_VAR(BOUNCETYPE_ENEMY); \
        SERIALIZE_ENUM_VAR(BOUNCETYPE_BUMPER); \
    SERIALIZE_ENUM_END();

//const GameMode GAMEMODE_UNKNOWN       = U32_INVALID;
const GameMode RAY_GAMEMODE_PLATFORMER  = 0;
const GameMode RAY_GAMEMODE_SHOOTER     = 1;
const GameMode RAY_GAMEMODE_WORLDMAP    = 2;
const GameMode RAY_GAMEMODE_COUNT       = 3; // To be incremented 

#define SERIALIZE_RAY_GAMEMODE(name,val) \
SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(GAMEMODE_UNKNOWN); \
    SERIALIZE_ENUM_VAR(RAY_GAMEMODE_PLATFORMER); \
    SERIALIZE_ENUM_VAR(RAY_GAMEMODE_SHOOTER); \
    SERIALIZE_ENUM_VAR(RAY_GAMEMODE_WORLDMAP); \
SERIALIZE_ENUM_END();

//const Faction FACTION_UNKNOWN     = U32_INVALID;
const Faction RAY_FACTION_NEUTRAL       = 0;
const Faction RAY_FACTION_FRIENDLY      = 1;
const Faction RAY_FACTION_ENEMY         = 2;
const Faction RAY_FACTION_MEGAENEMY     = 3;
const Faction RAY_FACTION_DARKTOON      = 4;
const Faction RAY_FACTION_FISH          = 5;
const Faction RAY_FACTION_DARKTOONWALL  = 6;
const Faction RAY_FACTION_PLUM          = 7;
const Faction RAY_FACTION_BREAKABLE     = 8;
const Faction RAY_FACTION_PLAYER        = 9;
const Faction RAY_FACTION_BOMBDEFUSED   = 10;
const Faction RAY_FACTION_RELICCHEST    = 11;
const Faction RAY_FACTION_GHOST         = 12;
const Faction RAY_FACTION_ELECTOON      = 13;
const Faction RAY_FACTION_BOSSMORAY     = 14;
const Faction RAY_FACTION_BUMPER        = 15;
const Faction RAY_FACTION_PROJECTILE    = 16;
const Faction RAY_FACTION_ENEMYFIRE     = 17;
const Faction RAY_FACTION_VULNERABLETOFIRE = 18;
const Faction RAY_FACTION_EXPLOSION     = 19;
const Faction RAY_FACTION_BLOWFISH      = 20;
const Faction RAY_FACTION_BUBBLE        = 21;
const Faction RAY_FACTION_ENEMYBULLET   = 22;
const Faction RAY_FACTION_MEGAENEMYEXCEPTBREAKABLE = 23;
const Faction RAY_FACTION_ALINFERNO = 24;
const Faction RAY_FACTION_ROBOT = 25;
const u32     RAY_FACTION_COUNT         = 26;

#define SERIALIZE_RAY_FACTION(name,val) \
SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(FACTION_UNKNOWN); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_NEUTRAL); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_FRIENDLY); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_ENEMY); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_MEGAENEMY); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_DARKTOON); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_FISH); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_DARKTOONWALL); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_PLUM); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_BREAKABLE); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_PLAYER); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_BOMBDEFUSED); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_RELICCHEST); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_GHOST); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_ELECTOON); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_BOSSMORAY); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_BUMPER); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_PROJECTILE); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_EXPLOSION); \
    SERIALIZE_ENUM_VAR(RAY_FACTION_BLOWFISH);\
    SERIALIZE_ENUM_VAR(RAY_FACTION_BUBBLE);\
    SERIALIZE_ENUM_VAR(RAY_FACTION_ENEMYBULLET);\
    SERIALIZE_ENUM_VAR(RAY_FACTION_MEGAENEMYEXCEPTBREAKABLE);\
SERIALIZE_ENUM_END();

enum EStargateStage
{
    STARGATESTAGE_SUCKIN = 0,
    STARGATESTAGE_WAIT,
    STARGATESTAGE_TRAVEL,
    STARGATESTAGE_END,
};

enum RelicType //CASA::VITA::TARIK::FRESCO GAMEPLAY
{
	RELIC_TYPE_NONE       = 0,
	RELIC_TYPE_INGAME     ,
	//RELIC_TYPE_NEAR
};

enum RelicState //CASA::VITA::TARIK::FRESCO GAMEPLAY
{
	RELIC_STATE_NONE       = 0,
	RELIC_STATE_NEW     ,
	RELIC_STATE_DUPLICATE
};

enum RelicStatus //CASA::VITA::TARIK::FRESCO GAMEPLAY
{
	RELIC_STATUS_LOCKED       = 0,
	RELIC_STATUS_UNLOCKED     ,
};

//CASA::VITA::TARIK::FRESCO GAMEPLAY
#define SERIALIZE_RELIC_TYPE(name,val) \
	SERIALIZE_ENUM_BEGIN(name,val); \
	SERIALIZE_ENUM_VAR(RELIC_TYPE_NONE); \
	SERIALIZE_ENUM_VAR(RELIC_TYPE_INGAME); \
	SERIALIZE_ENUM_END();

//CASA::VITA::TARIK::FRESCO GAMEPLAY
#define SERIALIZE_RELIC_STATUS(name,val) \
	SERIALIZE_ENUM_BEGIN(name,val); \
	SERIALIZE_ENUM_VAR(RELIC_STATUS_LOCKED); \
	SERIALIZE_ENUM_VAR(RELIC_STATUS_UNLOCKED); \
	SERIALIZE_ENUM_END();

// Worldmap
enum ESpot_State
{
    SPOT_STATE_CLOSED = 0,
    SPOT_STATE_NEW,
    SPOT_STATE_CANNOT_ENTER,
    SPOT_STATE_OPEN,
    SPOT_STATE_COMPLETED,
};

#define SERIALIZE_LEVEL_STATE(name,val) \
SERIALIZE_ENUM_BEGIN(name,val); \
    SERIALIZE_ENUM_VAR(SPOT_STATE_CLOSED); \
    SERIALIZE_ENUM_VAR(SPOT_STATE_NEW); \
    SERIALIZE_ENUM_VAR(SPOT_STATE_CANNOT_ENTER); \
    SERIALIZE_ENUM_VAR(SPOT_STATE_OPEN); \
    SERIALIZE_ENUM_VAR(SPOT_STATE_COMPLETED); \
SERIALIZE_ENUM_END();

enum EChallengeType 
{
    CHALLENGE_TIMEATTACK=1, 
    CHALLENGE_LUMATTACK1=2, 
    CHALLENGE_LUMATTACK2=4, 
    CHALLENGE_CUP=8,
    CHALLENGE_BEATENBOSS=16,
    CHALLENGE_LUMATTACK3=32,
}; 

#define s_RegionName_Death ITF_GET_STRINGID_CRC(death,2142372323)
#define s_RegionName_Frightened ITF_GET_STRINGID_CRC(afraid,1419060442)
#define s_RegionName_ChestArea ITF_GET_STRINGID_CRC(chestarea,3065974589)
#define s_RegionName_Current ITF_GET_STRINGID_CRC(current,2437737963)
#define s_RegionName_NoSoftColl ITF_GET_STRINGID_CRC(NoSoftColl,1005920238)
#define s_RegionName_NoFriendlyFire ITF_GET_STRINGID_CRC(NoFriendlyFire,636316220)

static const u32 s_dangerLevelDeath = 100;

// Behaviors names
#define s_BhvName_Death ITF_GET_STRINGID_CRC(DEATH,2142372323)
#define s_BhvName_Hit ITF_GET_STRINGID_CRC(HIT,2856859763)
#define s_BhvName_StartVacuum ITF_GET_STRINGID_CRC(START_VACCUMING,3032088790)
#define s_BhvName_Vacuuming ITF_GET_STRINGID_CRC(VACCUMING,42783283)
#define s_BhvName_Vacuumed ITF_GET_STRINGID_CRC(VACCUMED,1697274985)
#define s_BhvName_VacuumedEject ITF_GET_STRINGID_CRC(VACCUMED_EJECT,1414795698)

// Map config types
#define s_MapConfig_6cages ITF_GET_STRINGID_CRC(6cages,1882768436)
#define s_MapConfig_World ITF_GET_STRINGID_CRC(world,3307309411)
#define s_MapConfig_Platformer ITF_GET_STRINGID_CRC(platformer,1503006760)
#define s_MapConfig_Shooter ITF_GET_STRINGID_CRC(shooter,1762528103)
#define s_MapConfig_Chest ITF_GET_STRINGID_CRC(chest,2256079071)
#define s_MapConfig_Empty ITF_GET_STRINGID_CRC(empty,2085021599)

// World map tags
#define s_HomeMap ITF_GET_STRINGID_CRC(HomeMap,1612706167)
#define s_JU_A ITF_GET_STRINGID_CRC(JU_A,2778706121)
#define s_MU_A ITF_GET_STRINGID_CRC(MU_A,488324009)
#define s_FO_A ITF_GET_STRINGID_CRC(FO_A,8695403)
#define s_OC_A ITF_GET_STRINGID_CRC(OC_A,2734469878)
#define s_MO_A ITF_GET_STRINGID_CRC(MO_A,3745991623)
#define s_JU_B ITF_GET_STRINGID_CRC(JU_B,2419180662)
#define s_MU_B ITF_GET_STRINGID_CRC(MU_B,3433833306)
#define s_FO_B ITF_GET_STRINGID_CRC(FO_B,1718152063)
#define s_OC_B ITF_GET_STRINGID_CRC(OC_B,3036993652)
#define s_MO_B ITF_GET_STRINGID_CRC(MO_B,1011145385)
#define s_OC_A1 ITF_GET_STRINGID_CRC(OC_A1,4266947607)
#define s_MO_SHOOTER_A ITF_GET_STRINGID_CRC(MO_SHOOTER_A,2170218776)
#define s_TRIGGER_MOUNTAIN ITF_GET_STRINGID_CRC(TRIGGER_MOUNTAIN,611478250)
#define s_ju_bossmaster ITF_GET_STRINGID_CRC(ju_bossmaster,2141460896) // Jungle boss
#define s_BossBird ITF_GET_STRINGID_CRC(BossBird,3778756995)           // Music boss
#define s_OC_B3 ITF_GET_STRINGID_CRC(OC_B3,1116743380)                 // Ocean boss
#define s_FO_B3 ITF_GET_STRINGID_CRC(FO_B3,241303687)                  // Food boss
#define s_MO_B3 ITF_GET_STRINGID_CRC(MO_B3,3022165833)
#define s_MO_B4 ITF_GET_STRINGID_CRC(MO_B4,3020953941)
#define s_MO_SHOOTER_B ITF_GET_STRINGID_CRC(MO_SHOOTER_B,1192422309)
#define s_TRIGGER_DEATH ITF_GET_STRINGID_CRC(TRIGGER_DEATH,823271787)
#define s_DE_A1 ITF_GET_STRINGID_CRC(DE_A1,1147594655)

#define s_JU_A0				ITF_GET_STRINGID_CRC(JU_A0,1407647152)
#define s_JU_A1_GeyserBlast ITF_GET_STRINGID_CRC(JU_A1_GeyserBlast,3484250068)
#define s_JU_A3_GrowUrPath  ITF_GET_STRINGID_CRC(JU_A3_GrowUrPath,965046265)
#define s_JU_A4_GoWithFlow1 ITF_GET_STRINGID_CRC(JU_A4_GoWithFlow1,487768210)


// Fade types
#define s_FadeTypeNormal ITF_GET_STRINGID_CRC(normal,105362619)
#define s_FadeTypeNormalBlack ITF_GET_STRINGID_CRC(normalBlack,3109103539)
#define s_FadeTypeRotate ITF_GET_STRINGID_CRC(rotate,4210914729)

} // ITF

#endif // _ITF_RAY_GAMEPLAYTYPES_H_

