#include "precompiled_AudioSerializedData.h"
#include "adapters/AudioSerializedData/Wwise/WwiseEngineEvent.h"



namespace	ITF
{
BEGIN_SERIALIZATION(WwiseEngineEvent)
	SERIALIZE_MEMBER("GUID", m_guid);
	SERIALIZE_ENUM_BEGIN("EngineType", m_engineEventType);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_GAMEPLAY);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_CUTSCENE);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_MENU);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_TRC);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_VIDEO);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_DEBUG);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_PAUSE_WIIU);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_GAMEPLAY);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_CUTSCENE);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_MENU);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_TRC);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_VIDEO);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_DEBUG);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RESUME_WIIU);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_STOP_ALL);
    SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_START_MAP);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_MUTE_ALL);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_UNMUTE_ALL);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_CHECK_POINT_LOAD);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_RELOAD_MAP);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_HOT_RELOAD_MAP);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_SKIP_CINE);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_WWISE_QUITFROMGAME);
	SERIALIZE_ENUM_VAR(AUDIO_ENGEVT_COUNT);
	SERIALIZE_ENUM_END();
END_SERIALIZATION()
}

